// @chirag127/astro-shell/family-data
// ─────────────────────────────────────────────────────────────────────
// Single dynamic registry for every entity in the chirag127/oriz family.
//
// Apps import + render from this module; never hardcode the list.
// See: knowledge/decisions/architecture/dynamic-family-data-registry.md
//
// REGENERATED by scripts/discover-family.mjs (daily GH Action cron).
// Manual edits survive until the next discovery diff. To force a refresh:
//   node scripts/discover-family.mjs
// ─────────────────────────────────────────────────────────────────────

/* ───── Types ─────────────────────────────────────────────────────── */

export type AppCategory = 'hub' | 'personal' | 'content' | 'tools'
export type AppStatus = 'live' | 'beta' | 'planned'

export interface FamilyApp {
  /** Repo slug, e.g. `oriz-pages-blog-app`. */
  slug: string
  /** Display name, e.g. `oriz / blog`. */
  name: string
  /** Canonical URL. */
  url: string
  category: AppCategory
  tagline?: string
  status: AppStatus
}

export type PackageCategory = 'astro' | 'auth' | 'oriz' | 'omni'

export interface FamilyPackage {
  /** Short slug, e.g. `astro-shell`. */
  slug: string
  /** Full npm name, e.g. `@chirag127/astro-shell`. */
  npm: string
  /** GitHub repo, e.g. `chirag127/astro-shell-npm-pkg`. */
  ghRepo: string
  category: PackageCategory
  version?: string
  tagline?: string
}

export type ApiCategory = 'finance' | 'health' | 'utility' | 'global'
export type ApiStatus = 'live' | 'planned'

export interface FamilyApi {
  slug: string
  /** Canonical subdomain URL. */
  url: string
  rapidApiUrl?: string
  /** Open-API schema URL (typically GH Pages). */
  schemaUrl?: string
  category: ApiCategory
  status: ApiStatus
  tagline?: string
}

export type BookChannel = 'amazon' | 'gumroad' | 'leanpub' | 'github' | 'web'
export type BookStatus = 'live' | 'beta' | 'planned'

export interface FamilyBook {
  slug: string
  title: string
  cover?: string
  channels: BookChannel[]
  price?: string
  status: BookStatus
  tagline?: string
}

export type ExtensionSurface = 'chrome' | 'firefox' | 'edge' | 'vscode' | 'mcp'

export interface FamilyExtension {
  slug: string
  surface: ExtensionSurface
  url: string
  tagline?: string
}

export interface FamilySkill {
  slug: string
  install: string
  description: string
}

/* ───── FAMILY_APPS — 25 entries (1 hub + 1 personal + 8 content + 15 tools) ─ */

export const FAMILY_APPS: FamilyApp[] = [
  // Hub (1)
  {
    slug: 'home-app',
    name: 'oriz / home',
    url: 'https://oriz.in',
    category: 'hub',
    status: 'live',
    tagline: 'Family hub — index of every app, package, book, and API.',
  },

  // Personal (1)
  {
    slug: 'oriz-cs-me-app',
    name: 'CS',
    url: 'https://me.oriz.in',
    category: 'personal',
    status: 'live',
    tagline: "Chirag Singhal's personal site — hero, now, uses, CV, contact.",
  },

  // Content (8)
  {
    slug: 'oriz-financial-cards-app',
    name: 'oriz / financial-cards',
    url: 'https://financial-cards.oriz.in',
    category: 'content',
    status: 'live',
    tagline: 'India financial card intelligence — credit, debit, prepaid, travel/forex profiles.',
  },
  {
    slug: 'oriz-janaushdhi-app',
    name: 'oriz / janaushdhi',
    url: 'https://janaushdhi.oriz.in',
    category: 'content',
    status: 'planned',
    tagline: 'PMBJP generic medicine catalog — search, filter, compare, locate Kendras.',
  },
  {
    slug: 'oriz-lore-app',
    name: 'oriz / lore',
    url: 'https://book-lore.oriz.in',
    category: 'content',
    status: 'live',
    tagline: 'Ad-supported library of structured book summaries.',
  },
  {
    slug: 'oriz-ncert-app',
    name: 'oriz / ncert',
    url: 'https://books.oriz.in',
    category: 'content',
    status: 'live',
    tagline: 'Free NCERT textbook directory — browse, search, download every NCERT book.',
  },
  {
    slug: 'oriz-omni-post-app',
    name: 'oriz / omni',
    url: 'https://omni.oriz.in',
    category: 'content',
    status: 'beta',
    tagline: 'RSS-driven cross-poster — fans every blog post out to every platform with a public API.',
  },
  {
    slug: 'oriz-packages-catalog-app',
    name: 'oriz / packages',
    url: 'https://packages.oriz.in',
    category: 'content',
    status: 'planned',
    tagline: 'Auto-discovery catalog of every @chirag127/oriz npm package.',
  },
  {
    slug: 'oriz-pages-blog-app',
    name: 'oriz / blog',
    url: 'https://blog.oriz.in',
    category: 'content',
    status: 'live',
    tagline: 'Long-form writing on engineering, finance, and books.',
  },
  {
    slug: 'oriz-roam-journal-app',
    name: 'oriz / roam',
    url: 'https://journal.oriz.in',
    category: 'content',
    status: 'live',
    tagline: 'Privacy-first PWA journal — Tiptap editor, mood, tags, photos, optional E2EE.',
  },

  // Tools (15)
  {
    slug: 'oriz-cipher-crypto-tools-app',
    name: 'oriz / cipher',
    url: 'https://crypto.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Encryption, decryption, hashing, key-generation utilities.',
  },
  {
    slug: 'oriz-dice-random-tools-app',
    name: 'oriz / dice',
    url: 'https://random.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Dice rolls, coin flips, number generators, list shufflers, name pickers.',
  },
  {
    slug: 'oriz-echo-audio-tools-app',
    name: 'oriz / echo',
    url: 'https://audio.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Browser-based audio tools — trim, convert, extract, normalise.',
  },
  {
    slug: 'oriz-forge-dev-tools-app',
    name: 'oriz / forge',
    url: 'https://dev.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Developer toolbox — small, fast utilities for building and shipping code.',
  },
  {
    slug: 'oriz-grid-qr-tools-app',
    name: 'oriz / grid',
    url: 'https://qr.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Generate, decode, customise QR codes and barcodes.',
  },
  {
    slug: 'oriz-paisa-finance-tools-app',
    name: 'oriz / paisa',
    url: 'https://finance.oriz.in',
    category: 'tools',
    status: 'live',
    tagline: 'SIP, EMI, FIRE, tax calculators — math shown, browser-only, zero inputs sent.',
  },
  {
    slug: 'oriz-paper-print-tools-app',
    name: 'oriz / paper',
    url: 'https://print.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Print-ready generators — lined sheets, dot grids, planners, calendars, labels.',
  },
  {
    slug: 'oriz-pivot-data-tools-app',
    name: 'oriz / pivot',
    url: 'https://data.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Data/spreadsheet utilities — CSV/JSON/TSV transforms, pivots, sorts, dedupe.',
  },
  {
    slug: 'oriz-pixie-image-tools-app',
    name: 'oriz / pixie',
    url: 'https://image.oriz.in',
    category: 'tools',
    status: 'live',
    tagline: 'Compress, resize, crop, convert, watermark, upscale — all client-side.',
  },
  {
    slug: 'oriz-rank-seo-tools-app',
    name: 'oriz / rank',
    url: 'https://seo.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'SEO ranking and analysis tools — keyword research, SERP previews, meta-tag generators.',
  },
  {
    slug: 'oriz-reel-video-tools-app',
    name: 'oriz / reel',
    url: 'https://video.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Client-side video processing — trim, transcode, extract frames, change format.',
  },
  {
    slug: 'oriz-scribe-text-tools-app',
    name: 'oriz / scribe',
    url: 'https://text.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Text manipulation — case conversion, diffing, counting, formatting.',
  },
  {
    slug: 'oriz-shift-convert-tools-app',
    name: 'oriz / shift',
    url: 'https://convert.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Universal converter — units, formats, values across every "from X to Y" domain.',
  },
  {
    slug: 'oriz-slice-pdf-tools-app',
    name: 'oriz / slice',
    url: 'https://pdf.oriz.in',
    category: 'tools',
    status: 'live',
    tagline: 'Merge, split, compress, sign, redact, OCR — a free PDF toolkit, browser-only.',
  },
  {
    slug: 'oriz-vitals-health-tools-app',
    name: 'oriz / vitals',
    url: 'https://health.oriz.in',
    category: 'tools',
    status: 'planned',
    tagline: 'Health and fitness calculators — BMI, BMR, TDEE, body fat, macros, HR zones.',
  },
]

/* ───── FAMILY_PACKAGES — 23 entries on disk (22 astro-* canonical + auth/oriz/omni) ─ */

export const FAMILY_PACKAGES: FamilyPackage[] = [
  // Astro foundation (11)
  {
    slug: 'astro-billing',
    npm: '@chirag127/astro-billing',
    ghRepo: 'chirag127/astro-billing-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'Razorpay checkout + license-key verify + <Paywall> + <PriceTag>.',
  },
  {
    slug: 'astro-chrome',
    npm: '@chirag127/astro-chrome',
    ghRepo: 'chirag127/astro-chrome-npm-pkg',
    category: 'astro',
    version: '0.1.7',
    tagline: 'Shared visual chrome — Header, Footer, Wordmark, AccountPanel.',
  },
  {
    slug: 'astro-content',
    npm: '@chirag127/astro-content',
    ghRepo: 'chirag127/astro-content-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'Zod content schemas + RSS + Atom + JSON-Feed + sitemap + IndexNow + OG-card.',
  },
  {
    slug: 'astro-data',
    npm: '@chirag127/astro-data',
    ghRepo: 'chirag127/astro-data-npm-pkg',
    category: 'astro',
    version: '0.1.1',
    tagline: 'Data-fetching primitives — TanStack Query, typed Firestore helpers, LocalStorage hooks.',
  },
  {
    slug: 'astro-distribute',
    npm: '@chirag127/astro-distribute',
    ghRepo: 'chirag127/astro-distribute-npm-pkg',
    category: 'astro',
    version: '0.1.1',
    tagline: 'CLI wrapping PWABuilder (AAB / MSIX / iOS-project) and optional Tauri for desktop.',
  },
  {
    slug: 'astro-forms',
    npm: '@chirag127/astro-forms',
    ghRepo: 'chirag127/astro-forms-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'Form helpers — react-hook-form + Zod resolvers + shadcn-style wrappers + Web3Forms.',
  },
  {
    slug: 'astro-pwa',
    npm: '@chirag127/astro-pwa',
    ghRepo: 'chirag127/astro-pwa-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'Locked @vite-pwa/astro defaults for the chirag127 family.',
  },
  {
    slug: 'astro-shell',
    npm: '@chirag127/astro-shell',
    ghRepo: 'chirag127/astro-shell-npm-pkg',
    category: 'astro',
    version: '0.2.0',
    tagline: 'Astro 6 base layer — shell() defineConfig wrapper + design tokens + family-data registry.',
  },
  {
    slug: 'astro-test-utils',
    npm: '@chirag127/astro-test-utils',
    ghRepo: 'chirag127/astro-test-utils-npm-pkg',
    category: 'astro',
    version: '0.1.1',
    tagline: 'Common Vitest + Playwright + MSW + Firebase test fixtures.',
  },
  {
    slug: 'astro-tools',
    npm: '@chirag127/astro-tools',
    ghRepo: 'chirag127/astro-tools-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'ToolGrid + ToolCard + ToolPage components for utility sites.',
  },
  {
    slug: 'astro-widgets',
    npm: '@chirag127/astro-widgets',
    ghRepo: 'chirag127/astro-widgets-npm-pkg',
    category: 'astro',
    version: '0.1.0',
    tagline: 'Shared cross-app islands — <MultiSearch>, <StatusBanner>, <ConsentBanner>.',
  },

  // Auth (4)
  {
    slug: 'auth-cli',
    npm: '@chirag127/auth-cli',
    ghRepo: 'chirag127/auth-cli-npm-pkg',
    category: 'auth',
    version: '0.1.0',
    tagline: 'CLI auth — Firebase OAuth device-code flow + token store at ~/.config/oriz/auth.json.',
  },
  {
    slug: 'auth-core',
    npm: '@chirag127/auth-core',
    ghRepo: 'chirag127/auth-core-npm-pkg',
    category: 'auth',
    version: '0.1.0',
    tagline: 'Cross-surface auth primitives — auth.oriz.in URL helpers, Firebase ID-token verify.',
  },
  {
    slug: 'auth-vsc',
    npm: '@chirag127/auth-vsc',
    ghRepo: 'chirag127/auth-vsc-npm-pkg',
    category: 'auth',
    version: '0.1.0',
    tagline: 'VS Code extension auth — vscode.authentication API + secure-storage.',
  },
  {
    slug: 'auth-wxt',
    npm: '@chirag127/auth-wxt',
    ghRepo: 'chirag127/auth-wxt-npm-pkg',
    category: 'auth',
    version: '0.1.0',
    tagline: 'Browser-extension auth — chrome.identity.launchWebAuthFlow through auth.oriz.in.',
  },

  // Oriz packages (7)
  {
    slug: 'oriz-ai-providers',
    npm: '@chirag127/oriz-ai-providers',
    ghRepo: 'chirag127/oriz-ai-providers-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Thin wrapper around 20 free LLM APIs (OVHcloud, LLM7, Pollinations, Cerebras, Groq...).',
  },
  {
    slug: 'oriz-analytics',
    npm: '@chirag127/oriz-analytics',
    ghRepo: 'chirag127/oriz-analytics-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Single wrapper around Cloudflare Web Analytics + GA4 + Microsoft Clarity + Sentry.',
  },
  {
    slug: 'oriz-book-build',
    npm: '@chirag127/oriz-book-build',
    ghRepo: 'chirag127/oriz-book-build-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Pandoc-wrapping CLI — builds EPUB3 / PDF / MOBI / Markua from a manuscript.',
  },
  {
    slug: 'oriz-consent',
    npm: '@chirag127/oriz-consent',
    ghRepo: 'chirag127/oriz-consent-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Klaro-based consent manager — GDPR + UK + India DPDP + US GPC signal handling.',
  },
  {
    slug: 'oriz-rate-limit',
    npm: '@chirag127/oriz-rate-limit',
    ghRepo: 'chirag127/oriz-rate-limit-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Per-user usage caps for Free/Pro/Max tiers. Edge-friendly token bucket.',
  },
  {
    slug: 'oriz-seo',
    npm: '@chirag127/oriz-seo',
    ghRepo: 'chirag127/oriz-seo-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Sitemap.xml + IndexNow ping + JSON-LD + dynamic OG image generation via satori.',
  },
  {
    slug: 'oriz-ui',
    npm: '@chirag127/oriz-ui',
    ghRepo: 'chirag127/oriz-ui-npm-pkg',
    category: 'oriz',
    version: '0.1.0',
    tagline: 'Shared Oriz UI — ContactForm + widgets used across the family.',
  },

  // Omni (1)
  {
    slug: 'omni-publish',
    npm: '@chirag127/omni-publish',
    ghRepo: 'chirag127/omni-publish-npm-pkg',
    category: 'omni',
    version: '0.1.2',
    tagline: 'Auto-publish release notes / blog posts to dev.to, Hashnode, Bluesky, Mastodon...',
  },
]

/* ───── FAMILY_APIS — 14 entries (2 live + 12 planned) ─────────── */

export const FAMILY_APIS: FamilyApi[] = [
  // Live
  {
    slug: 'fii-dii-api',
    url: 'https://fii-dii.api.oriz.in',
    rapidApiUrl: 'https://rapidapi.com/chirag127/api/oriz-fii-dii',
    schemaUrl: 'https://chirag127.github.io/fii-dii-api/openapi.json',
    category: 'finance',
    status: 'live',
    tagline: 'Daily FII/DII activity in Indian equity markets.',
  },
  {
    slug: 'janaushdhi-api',
    url: 'https://janaushdhi.api.oriz.in',
    rapidApiUrl: 'https://rapidapi.com/chirag127/api/oriz-janaushdhi',
    schemaUrl: 'https://chirag127.github.io/janaushdhi-api/openapi.json',
    category: 'health',
    status: 'live',
    tagline: 'PMBJP generic medicine catalog API.',
  },

  // Planned (12)
  {
    slug: 'sip-emi-api',
    url: 'https://sip-emi.api.oriz.in',
    category: 'finance',
    status: 'planned',
    tagline: 'SIP and EMI calculators.',
  },
  {
    slug: 'tax-india-api',
    url: 'https://tax-india.api.oriz.in',
    category: 'finance',
    status: 'planned',
    tagline: 'Indian income-tax calculator (old/new regime).',
  },
  {
    slug: 'ifsc-api',
    url: 'https://ifsc.api.oriz.in',
    category: 'finance',
    status: 'planned',
    tagline: 'IFSC code lookup + bank branch directory.',
  },
  {
    slug: 'gst-api',
    url: 'https://gst.api.oriz.in',
    category: 'finance',
    status: 'planned',
    tagline: 'GSTIN lookup + HSN/SAC code search.',
  },
  {
    slug: 'pincode-api',
    url: 'https://pincode.api.oriz.in',
    category: 'utility',
    status: 'planned',
    tagline: 'Indian pincode lookup + post-office directory.',
  },
  {
    slug: 'bmi-api',
    url: 'https://bmi.api.oriz.in',
    category: 'health',
    status: 'planned',
    tagline: 'BMI / BMR / TDEE / body-fat calculators.',
  },
  {
    slug: 'qr-api',
    url: 'https://qr.api.oriz.in',
    category: 'utility',
    status: 'planned',
    tagline: 'QR code generation + barcode decoding.',
  },
  {
    slug: 'shorten-api',
    url: 'https://shorten.api.oriz.in',
    category: 'utility',
    status: 'planned',
    tagline: 'URL shortener with QR + analytics.',
  },
  {
    slug: 'unit-convert-api',
    url: 'https://convert.api.oriz.in',
    category: 'utility',
    status: 'planned',
    tagline: 'Universal unit converter — length, mass, currency, temperature.',
  },
  {
    slug: 'currency-api',
    url: 'https://currency.api.oriz.in',
    category: 'global',
    status: 'planned',
    tagline: 'Free-tier FX rates with EUR baseline.',
  },
  {
    slug: 'holidays-api',
    url: 'https://holidays.api.oriz.in',
    category: 'global',
    status: 'planned',
    tagline: 'Public holidays directory by country + year.',
  },
  {
    slug: 'timezones-api',
    url: 'https://timezones.api.oriz.in',
    category: 'global',
    status: 'planned',
    tagline: 'Timezone DB + DST transitions + tz-name lookup.',
  },
]

/* ───── FAMILY_BOOKS — 5 entries ──────────────────────────────────── */

export const FAMILY_BOOKS: FamilyBook[] = [
  {
    slug: 'astro-from-scratch-book',
    title: 'Astro from Scratch',
    channels: ['gumroad', 'leanpub', 'github'],
    price: '$19',
    status: 'planned',
    tagline: 'Build production-grade content sites with Astro 6.',
  },
  {
    slug: 'firebase-the-hard-parts-book',
    title: 'Firebase: The Hard Parts',
    channels: ['gumroad', 'leanpub'],
    price: '$24',
    status: 'planned',
    tagline: 'Auth, Firestore security rules, and Cloud Functions for real apps.',
  },
  {
    slug: 'pwa-without-frameworks-book',
    title: 'PWAs Without Frameworks',
    channels: ['gumroad', 'github'],
    price: '$14',
    status: 'planned',
    tagline: 'Service workers, offline-first, install prompts — plain web platform.',
  },
  {
    slug: 'cloudflare-pages-and-workers-book',
    title: 'Cloudflare Pages & Workers',
    channels: ['leanpub'],
    price: '$19',
    status: 'planned',
    tagline: 'Edge deployment, KV, D1, Durable Objects, and Pages Functions.',
  },
  {
    slug: 'monorepo-with-pnpm-book',
    title: 'Monorepo with pnpm + Turborepo',
    channels: ['gumroad'],
    price: '$19',
    status: 'planned',
    tagline: 'Workspace setup, build pipelines, caching, and CI for monorepos.',
  },
]

/* ───── FAMILY_EXTENSIONS — 0 (none shipped yet) ─────────────────── */

export const FAMILY_EXTENSIONS: FamilyExtension[] = []

/* ───── FAMILY_SKILLS — 2 entries ─────────────────────────────────── */

export const FAMILY_SKILLS: FamilySkill[] = [
  {
    slug: 'agents-md-sync-skill',
    install: 'npx skills add chirag127/skill-agents-md-sync -g -a claude-code',
    description: 'Sync AGENTS.md across all per-agent deployed copies.',
  },
  {
    slug: 'claude-code-mcq-notes-skill',
    install: 'npx skills add chirag127/skill-claude-code-mcq-notes -g -a claude-code',
    description: 'Notes + repros on the Claude Code AskUserQuestion MCQ widget quirks.',
  },
]

/* ───── Aggregate helpers ─────────────────────────────────────────── */

export interface FamilyDataSummary {
  apps: number
  packages: number
  apis: number
  books: number
  extensions: number
  skills: number
  total: number
}

export function familyDataSummary(): FamilyDataSummary {
  const apps = FAMILY_APPS.length
  const packages = FAMILY_PACKAGES.length
  const apis = FAMILY_APIS.length
  const books = FAMILY_BOOKS.length
  const extensions = FAMILY_EXTENSIONS.length
  const skills = FAMILY_SKILLS.length
  return {
    apps,
    packages,
    apis,
    books,
    extensions,
    skills,
    total: apps + packages + apis + books + extensions + skills,
  }
}
